version: 2

build:
  os: ubuntu-lts-latest
  # apt_packages:
  #   - just
  tools:
    python: "3.12"
  jobs:
    build:
      html:
        # this would be preferable but readthedocs' ubuntu doesn't seem to have `just` available as a package
        # - just doc ${READTHEDOCS_OUTPUT}/html
        - mkdir -p ${READTHEDOCS_OUTPUT}/html
        - uv run --group doc pdoc --output-directory ${READTHEDOCS_OUTPUT}/html --no-include-undocumented --docformat markdown --search transformnd
